pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref'],
      // [key: 'email', value: '$.repository.owner.email'],
      [key: 'url', value: '$.repository']
     ],

     causeString: 'Triggered on $ref',

     token: 'abc123',
     tokenCredentialId: '',

     printContributedVariables: true,
     printPostContent: true,

     silentResponse: false,
     
     shouldNotFlatten: false,

     regexpFilterText: '$ref',
     regexpFilterExpression: 'refs/heads/'
    )
  }
  stages {
    stage('Some step2') {
      steps {
        sh "echo $ref"
        sh "echo $url"
      }
    }
  }
}
